### ISSUE TITLE
Non-Relu LLM inference sparse activation speedup

### ISSUE THREAD

**Issue by pkumc** [SJTU-IPADS/Bamboo#1]
@YixinSong-e @ZeyuMi Very excellent work! By the way, have you compared the inference speedup of Non-Relu LLM, such as original mistral-7B/llama-7B? If non-Relu LLM is also sparse in a degree(Figure 1 in [ReLU2 Wins paper](https://arxiv.org/pdf/2402.03804.pdf)), maybe we can directly accelerate inference by sparse activation without extra expensive _relufication_ step. 
So I'm not sure if you have done some non-Relu LLM experiments? If the result is not positive, which reason could be the key factor? 
1. Non-Relu LLM is not sparse enough to get a significant speedup.
2. It's harder to predict the activation sparsity for non-Relu LLM.
Or some others? Thank you!

**Comment by jeremyyx** [comment]
Thank you for your interest. It is because the second factor. It is very hard to predict the activated neurons for non-Relu LLM, especially for SwiGLU based LLM because of the negetive non-linear activation.

**Comment by pkumc** [comment]
> Thank you for your interest. It is because the second factor. It is very hard to predict the activated neurons for non-Relu LLM, especially for SwiGLU based LLM because of the negetive non-linear activation.

Ok, I got it, thx.
In the future work, you mentioned Mixtral 8x7B level sparse activation model. Does it mean to train a Relu-based MoE model? I found [some work](https://github.com/Lucky-Lance/Expert_Sparsity) already prune experts(8 experts -> 4 expert) and skip expert(select top2 -> top1). I'm not sure if there still have space for further sparse activation.

**Comment by jeremyyx** [comment]
> > Thank you for your interest. It is because the second factor. It is very hard to predict the activated neurons for non-Relu LLM, especially for SwiGLU based LLM because of the negetive non-linear activation.
> 
> Ok, I got it, thx. In the future work, you mentioned Mixtral 8x7B level sparse activation model. Does it mean to train a Relu-based MoE model? I found [some work](https://github.com/Lucky-Lance/Expert_Sparsity) already prune experts(8 experts -> 4 expert) and skip expert(select top2 -> top1). I'm not sure if there still have space for further sparse activation.

We extend ReLUfication to MoE models. You can refer to https://arxiv.org/abs/2406.05955
